//! Build-time-baked cartridge registry version.
//!
//! Generated by `build.rs` from the `MFR_CARTRIDGE_REGISTRY_VERSION` env var
//! (sourced from `schemas/cartridge-registry/registry-version.txt` by the workspace build tool).
//! See the build script's module doc for the contract. This is the version
//! this build speaks to the cartridge registry: it fetches the manifest at the
//! versioned path and rejects any manifest whose `registryVersion` differs.

include!(concat!(env!("OUT_DIR"), "/cartridge_registry_version.rs"));
