//! Build-time-baked fabric registry manifest version.
//!
//! Generated by `build.rs` from the `MFR_FABRIC_MANIFEST_VERSION` env var
//! (sourced from `fabric/manifest-version.txt` by the workspace build tool). See the build
//! script's module doc for the contract.

include!(concat!(env!("OUT_DIR"), "/fabric_manifest_version.rs"));
