//! GENERATED by scripts/vendor-stub-cartridges.py — DO NOT EDIT.
//!
//! The canonical stubs live in the capdag-stub-cartridges repository; this file
//! is a vendored copy so a published capdag can scaffold offline. Change a stub
//! there, then re-run the vendor script in every mirror.

/// One file a scaffold writes: its path inside the project, its contents,
/// and whether the host must be able to exec it.
pub struct StubFile {
    pub dest: &'static str,
    pub contents: &'static str,
    pub executable: bool,
}

/// One scaffoldable language.
pub struct StubLanguage {
    pub id: &'static str,
    pub flag: &'static str,
    pub display: &'static str,
    /// The executable the host launches, placeholder-substituted like any
    /// other rendered path.
    pub entry: &'static str,
    /// Commands that turn the sources into `entry` — empty for interpreted
    /// languages, which have nothing to build.
    pub build: &'static [&'static str],
    pub runtime_package: &'static str,
    pub runtime_registry: &'static str,
    pub runtime_install: &'static str,
    pub files: &'static [StubFile],
}

/// The token replaced by the project name in every file's CONTENTS and in
/// its destination path and entry.
pub const STUB_PLACEHOLDER: &str = r#"__CARTRIDGE_NAME__"#;

pub const STUB_CONTRACT_VERSION: u32 = 1;

/// Every language `capdag new` can scaffold, in contract order.
pub const STUB_LANGUAGES: &[StubLanguage] = &[
    StubLanguage {
        id: r#"python"#,
        flag: r#"--python"#,
        display: r#"Python"#,
        entry: r#"cartridge.py"#,
        build: &[],
        runtime_package: r#"capdag"#,
        runtime_registry: r#"PyPI"#,
        runtime_install: r#"pip install capdag"#,
        files: &[
            StubFile {
                dest: r#"cartridge.py"#,
                contents: r#"#!/usr/bin/env python3
"""__CARTRIDGE_NAME__ — a MachineFabric cartridge (Python), scaffolded by `capdag new`.

Reads UTF-8 text on stdin and emits a single tag word: `positive`,
`neutral`, or `negative`.

The judgment is made by a REAL model: this cartridge does no inference itself,
it PEER-CALLS the `classify-en` cap and whichever model cartridge the host has
installed answers it. That is the shape most cartridges want — own the domain
logic, delegate the model — and it is what makes this the smallest useful
cartridge rather than a toy: one custom cap, one Op that calls a peer, one
manifest, one main().

Develop it with:
    capdag dev-install .          # install/update under the local `dev` slug
    echo "I love this" | capdag __CARTRIDGE_NAME__
    # edit the labels or the peer cap, then re-run `capdag dev-install .`
"""

import json

from capdag.bifaci.cartridge_runtime import (
    CartridgeRuntime,
    Request,
    WET_KEY_REQUEST,
    demux_peer_response,
)
from capdag.cap.caller import CapArgumentValue
from capdag.bifaci.manifest import CapManifest, default_group
from capdag.cap.definition import (
    Cap,
    CapArg,
    CapOutput,
    PositionSource,
    StdinSource,
)
from capdag.standard.caps import CAP_IDENTITY
from capdag.urn.cap_urn import CapUrn, CapUrnBuilder
from ops import DryContext, Op, OpMetadata, WetContext


# --- The peer cap this cartridge delegates to. ------------------------------

# `classify-en` — closed-set labeling by a real model, provided by whichever
# model cartridge the host has installed.
#
# The labels are token-level constrained to the set we pass, so the answer is
# always one of them: a hallucinated label is impossible by construction, and
# this cartridge does not have to defend against one.
CLASSIFY_CAP = (
    'cap:classify;constrained;in="media:enc=utf-8";language=en;'
    'out="media:fmt=json;record;semantic-judgment"'
)

# The item being classified, and the allowed labels — both addressed by MEDIA
# URN, which is how a peer call names its arguments.
CLASSIFY_ITEM_MEDIA = "media:enc=utf-8"
CLASSIFY_LABELS_MEDIA = "media:enc=utf-8;label-set"

LABELS = "positive,neutral,negative"


# --- Op — implements the cap. -----------------------------------------------

class TagOp(Op):
    async def perform(self, dry: DryContext, wet: WetContext) -> None:
        req: Request = wet.get_required(WET_KEY_REQUEST)
        # Drain the (finite) input stream(s) and decode as UTF-8 text.
        text = req.take_input().collect_all_bytes().decode("utf-8")

        emitter = req.emitter()
        emitter.start(False)

        # Ask the model cartridge. Arguments are addressed by media URN, not by
        # position.
        peer_frames = req.peer().invoke(
            CLASSIFY_CAP,
            [
                CapArgumentValue(CLASSIFY_ITEM_MEDIA, text.encode("utf-8")),
                CapArgumentValue(CLASSIFY_LABELS_MEDIA, LABELS.encode("utf-8")),
            ],
        )

        # FORWARDING collector: inference is slow and the model reports progress
        # as it goes. A plain collect_bytes REJECTS those LOG frames rather than
        # discarding them silently, so a peer that talks must be collected
        # through a forwarder. The peer's 0..1 progress is rescaled into the
        # 0.0..0.9 slice of ours, leaving the last tenth for our own work below.
        judgment = demux_peer_response(peer_frames).collect_bytes_forwarding(
            emitter, 0.0, 0.9
        )

        # The judgment record is {"label", "confidence", "reason"}; the label is
        # one of the labels we asked for.
        try:
            record = json.loads(judgment)
        except ValueError as error:
            raise RuntimeError(
                f"classify returned something that is not a semantic-judgment record: {error}"
            ) from error
        label = record.get("label")
        if not isinstance(label, str):
            raise RuntimeError("the semantic-judgment record has no string `label` field")

        emitter.finish(1.0, f"classified as {label}")
        emitter.emit_cbor(label)

    def metadata(self) -> OpMetadata:
        return (
            OpMetadata.builder("TagOp")
            .description("Classify text as positive / neutral / negative")
            .build()
        )


# --- URN + manifest. Media/cap URNs are seeded from the project name so they -
#     are unique per project and never collide with the published fabric. -----

IN_MEDIA = "media:enc=utf-8;__CARTRIDGE_NAME__-input"
OUT_MEDIA = "media:enc=utf-8;__CARTRIDGE_NAME__-tag"


def _cap_urn() -> CapUrn:
    """Build the cap URN ONCE via the builder, so the string we register with
    matches the runtime's canonical (alphabetically-sorted) byte form."""
    return (
        CapUrnBuilder()
        .marker("__CARTRIDGE_NAME__")
        .in_spec(IN_MEDIA)
        .out_spec(OUT_MEDIA)
        .build()
    )


CAP_URN: str = _cap_urn().to_string()


def build_manifest() -> CapManifest:
    cap = Cap(_cap_urn(), "__CARTRIDGE_NAME__", ["__CARTRIDGE_NAME__"])
    cap.cap_description = "Classify a piece of text as positive, neutral, or negative."
    cap.args = [
        CapArg(
            media_urn=IN_MEDIA,
            required=True,
            sources=[StdinSource(IN_MEDIA), PositionSource(0)],
            arg_description="UTF-8 text to classify.",
        )
    ]
    cap.output = CapOutput(
        media_urn=OUT_MEDIA,
        output_description="One of the literal strings 'positive', 'neutral', or 'negative'.",
    )

    # Every cartridge advertises CAP_IDENTITY; the runtime auto-registers its handler.
    identity = Cap(CapUrn.from_string(CAP_IDENTITY), "Identity", ["identity"])

    return CapManifest(
        name="__CARTRIDGE_NAME__",
        version="0.1.0",
        channel="nightly",          # 'nightly' or 'release'; nightly for dev.
        registry_url=None,           # None => dev cartridge (installed locally).
        description="Classify a piece of text as positive, neutral, or negative.",
        cap_groups=[default_group([identity, cap])],
    )


def main() -> None:
    runtime = CartridgeRuntime.with_manifest(build_manifest())
    runtime.register_op_type(CAP_URN, TagOp)
    runtime.run()


if __name__ == "__main__":
    main()
"#,
                executable: true,
            },
            StubFile {
                dest: r#"README.md"#,
                contents: r#"# __CARTRIDGE_NAME__

A MachineFabric cartridge scaffolded by `capdag new`. It reads UTF-8 text on
stdin and emits `positive`, `neutral`, or `negative`.

## Develop

```bash
# 1. Install capdag (the cartridge runtime) so `cartridge.py` can import it:
pip install capdag

# 2. Install this cartridge under the local `dev` slug:
capdag dev-install .

# 3. Run your cap through the capdag host:
echo "I love this" | capdag __CARTRIDGE_NAME__
# => positive

# 4. Edit the labels or the peer cap in cartridge.py, then re-run step 2:
capdag dev-install .
```

## It needs the host

This cartridge does not classify anything itself — it PEER-CALLS `classify-en`
and a model cartridge answers. Peer calls are routed by the capdag host, so
running the built entry directly (`./__CARTRIDGE_NAME__ __CARTRIDGE_NAME__`)
fails with `Peer invocation not supported in this context`. That is correct, not
a bug: run it through `capdag __CARTRIDGE_NAME__`, which hosts the cartridge and
routes the call.

A model cartridge providing `classify-en` must be installed. The first run
downloads the model, which is why the peer reports progress and why this
cartridge forwards it.

The cap is a *dev* cap: it is not published to the fabric, so you can develop
and run it locally as long as its alias (`__CARTRIDGE_NAME__`) does not collide
with a published cap.
"#,
                executable: false,
            },
            StubFile {
                dest: r#".gitignore"#,
                contents: r#".venv/
__pycache__/
*.pyc
.pytest_cache/
cartridge.json
"#,
                executable: false,
            },
        ],
    },
    StubLanguage {
        id: r#"rust"#,
        flag: r#"--rust"#,
        display: r#"Rust"#,
        entry: r#"target/release/__CARTRIDGE_NAME__"#,
        build: &[r#"cargo build --release"#],
        runtime_package: r#"capdag"#,
        runtime_registry: r#"git tag"#,
        runtime_install: r#"cargo build (the dependency is declared in Cargo.toml)"#,
        files: &[
            StubFile {
                dest: r#"src/main.rs"#,
                contents: r##"//! __CARTRIDGE_NAME__ — a MachineFabric cartridge (Rust), scaffolded by `capdag new`.
//!
//! Reads UTF-8 text on stdin and emits a single tag word: `positive`,
//! `neutral`, or `negative`.
//!
//! The judgment is made by a REAL model: this cartridge does no inference
//! itself, it PEER-CALLS the `classify-en` cap and whichever model cartridge
//! the host has installed answers it. That is the shape most cartridges want —
//! own the domain logic, delegate the model — and it is what makes this the
//! smallest useful cartridge rather than a toy: one custom cap, one Op that
//! calls a peer, one manifest, one main().
//!
//! Develop it with:
//!     cargo build --release                     # the entry the host launches
//!     capdag dev-install .                      # install under the local `dev` slug
//!     echo "I love this" | capdag __CARTRIDGE_NAME__
//!     # edit the labels or the peer cap, then re-run both to update

use anyhow::Result;
use capdag::standard::caps::identity_urn;
use capdag::{
    async_trait, ArgSource, Cap, CapArg, CapGroup, CapManifest, CapOutput, CapUrn, CapUrnBuilder,
    CartridgeChannel, CartridgeRuntime, DryContext, Op, OpError, OpMetadata, OpResult, Request,
    WetContext, WET_KEY_REQUEST,
};
use serde_json::Value as JsonValue;
use std::sync::Arc;

// --- The peer cap this cartridge delegates to. ------------------------------

/// `classify-en` — closed-set labeling by a real model, provided by whichever
/// model cartridge the host has installed.
///
/// The labels are token-level constrained to the set we pass, so the answer is
/// always one of them: a hallucinated label is impossible by construction, and
/// this cartridge does not have to defend against one.
const CLASSIFY_CAP: &str =
    r#"cap:classify;constrained;in="media:enc=utf-8";language=en;out="media:fmt=json;record;semantic-judgment""#;

/// The item being classified, and the allowed labels — both addressed by MEDIA
/// URN, which is how a peer call names its arguments.
const CLASSIFY_ITEM_MEDIA: &str = "media:enc=utf-8";
const CLASSIFY_LABELS_MEDIA: &str = "media:enc=utf-8;label-set";

const LABELS: &str = "positive,neutral,negative";

// --- Op — implements the cap. -----------------------------------------------

#[derive(Default)]
struct TagOp;

#[async_trait]
impl Op<()> for TagOp {
    async fn perform(&self, _dry: &mut DryContext, wet: &mut WetContext) -> OpResult<()> {
        let req: Arc<Request> = wet
            .get_required::<Request>(WET_KEY_REQUEST)
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?;

        // Drain the (finite) input stream and decode as UTF-8 text.
        let streams = req
            .take_input()
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?
            .collect_streams()
            .await
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?;
        let bytes: Vec<u8> = streams.into_iter().flat_map(|(_, body, _)| body).collect();

        let output = req.output();
        output
            .start(false, None)
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?;

        // Ask the model cartridge. `call_with_bytes` opens the call, writes each
        // argument, and finishes it; arguments are addressed by media URN, not
        // by position.
        let response = req
            .peer()
            .call_with_bytes(
                CLASSIFY_CAP,
                &[
                    (CLASSIFY_ITEM_MEDIA, bytes.as_slice()),
                    (CLASSIFY_LABELS_MEDIA, LABELS.as_bytes()),
                ],
            )
            .await
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?;

        // FORWARDING collector: inference is slow and the model reports
        // progress as it goes. A plain `collect_bytes` REJECTS those LOG frames
        // rather than discarding them silently, so a peer that talks must be
        // collected through a forwarder. The peer's 0..1 progress is rescaled
        // into the 0.0..0.9 slice of ours, leaving the last tenth for our own
        // work below.
        let judgment = response
            .collect_bytes_forwarding(output, 0.0, 0.9)
            .await
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))?;

        // The judgment record is {"label", "confidence", "reason"}; the label is
        // one of the labels we asked for.
        let record: JsonValue = serde_json::from_slice(&judgment).map_err(|e| {
            OpError::ExecutionFailed(format!(
                "classify returned something that is not a semantic-judgment record: {e}"
            ))
        })?;
        let label = record
            .get("label")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                OpError::ExecutionFailed(
                    "the semantic-judgment record has no string `label` field".to_string(),
                )
            })?;

        output.finish(1.0, &format!("classified as {label}"));
        output
            .emit_cbor(&ciborium::Value::Text(label.to_string()))
            .await
            .map_err(|e| OpError::ExecutionFailed(e.to_string()))
    }

    fn metadata(&self) -> OpMetadata {
        OpMetadata::builder("TagOp")
            .description("Classify text as positive / neutral / negative")
            .build()
    }
}

// --- URN + manifest. Media/cap URNs are seeded from the project name so they -
//     are unique per project and never collide with the published fabric. -----

const IN_MEDIA: &str = "media:enc=utf-8;__CARTRIDGE_NAME__-input";
const OUT_MEDIA: &str = "media:enc=utf-8;__CARTRIDGE_NAME__-tag";

/// Build the cap URN ONCE via the builder, so the string we register with
/// matches the runtime's canonical (alphabetically-sorted) byte form.
fn cap_urn() -> CapUrn {
    CapUrnBuilder::new()
        .marker("__CARTRIDGE_NAME__")
        .in_spec(IN_MEDIA)
        .out_spec(OUT_MEDIA)
        .build()
        .expect("BUG: the scaffolded cap URN is invalid")
}

fn build_manifest() -> CapManifest {
    let mut cap = Cap::new(
        cap_urn(),
        "__CARTRIDGE_NAME__".to_string(),
        vec!["__CARTRIDGE_NAME__".to_string()],
    );
    cap.cap_description =
        Some("Classify a piece of text as positive, neutral, or negative.".to_string());
    cap.add_arg(CapArg::with_description(
        IN_MEDIA,
        true,
        vec![
            ArgSource::Stdin {
                stdin: IN_MEDIA.to_string(),
            },
            ArgSource::Position { position: 0 },
        ],
        "UTF-8 text to classify.".to_string(),
    ));
    cap.set_output(CapOutput {
        media_urn: OUT_MEDIA.to_string(),
        output_description:
            "One of the literal strings 'positive', 'neutral', or 'negative'.".to_string(),
        is_sequence: false,
        metadata: None,
    });

    // Every cartridge advertises CAP_IDENTITY; the runtime auto-registers its handler.
    let identity = Cap::new(
        identity_urn(),
        "Identity".to_string(),
        vec!["identity".to_string()],
    );

    CapManifest::new(
        "__CARTRIDGE_NAME__".to_string(),
        "0.1.0".to_string(),
        CartridgeChannel::Nightly, // 'Release' or 'Nightly'; nightly for dev.
        None,                      // None => dev cartridge (installed locally).
        "Classify a piece of text as positive, neutral, or negative.".to_string(),
        vec![CapGroup {
            name: "default".to_string(),
            caps: vec![identity, cap],
            adapter_urns: Vec::new(),
        }],
    )
}

#[tokio::main]
async fn main() -> Result<()> {
    let mut runtime = CartridgeRuntime::with_manifest(build_manifest());
    runtime.register_op_type::<TagOp>(&cap_urn().to_string());
    // `?`: the runtime returns its own RuntimeError, which anyhow adopts.
    runtime.run().await?;
    Ok(())
}
"##,
                executable: false,
            },
            StubFile {
                dest: r#"Cargo.toml"#,
                contents: r#"[package]
name = "__CARTRIDGE_NAME__"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
# capdag is resolved from a git TAG, not crates.io: it depends on ffmpeg-bundle,
# which is unpublishable, and cargo requires a version requirement on every
# dependency. The tag is stamped from capdag's own version.txt, so it tracks
# what `dx publish capdag` tags instead of drifting until someone notices.
capdag = { git = "https://github.com/machinefabric/capdag-rs", tag = "v1.656.33" }
ciborium = "0.2"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
"#,
                executable: false,
            },
            StubFile {
                dest: r#".cargo/config.toml"#,
                contents: r#"# capdag's build script bakes two versions into the crate and treats both as
# MANDATORY — a plain `cargo build` without them fails with a message telling
# you to build through `dx`, which is the MachineFabric workspace's tool and not
# something a cartridge project has. Setting them here is what makes `cargo
# build` work in a scaffolded project.
#
# They pin which fabric manifest and which cartridge registry regime this
# cartridge is compiled against, and they must match the capdag version above.
[env]
MFR_FABRIC_MANIFEST_VERSION = "4"
MFR_CARTRIDGE_REGISTRY_VERSION = "1"
"#,
                executable: false,
            },
            StubFile {
                dest: r#"README.md"#,
                contents: r#"# __CARTRIDGE_NAME__

A MachineFabric cartridge scaffolded by `capdag new`. It reads UTF-8 text on
stdin and emits `positive`, `neutral`, or `negative`.

## Develop

```bash
# 1. Build the entry the host launches:
cargo build --release

# 2. Install this cartridge under the local `dev` slug:
capdag dev-install .

# 3. Run your cap through the capdag host:
echo "I love this" | capdag __CARTRIDGE_NAME__
# => positive

# 4. Edit the labels or the peer cap in src/main.rs, then re-run steps 1-2:
cargo build --release && capdag dev-install .
```

Unlike the Python cartridge, the entry here is a COMPILED binary, so an edit
does not reach the host until you rebuild.

## `.cargo/config.toml`

The `capdag` crate's build script bakes two versions into the crate and treats
both as mandatory: `MFR_FABRIC_MANIFEST_VERSION` (which fabric manifest this
cartridge is compiled against) and `MFR_CARTRIDGE_REGISTRY_VERSION` (which
cartridge registry regime). Without them `cargo build` fails with a message
telling you to build through `dx`, which is the MachineFabric workspace's own
tool — not something a cartridge project has.

`.cargo/config.toml` sets them, which is what makes a plain `cargo build` work
here. Change them only together with the `capdag` version in `Cargo.toml`.

## It needs the host

This cartridge does not classify anything itself — it PEER-CALLS `classify-en`
and a model cartridge answers. Peer calls are routed by the capdag host, so
running the built entry directly (`./__CARTRIDGE_NAME__ __CARTRIDGE_NAME__`)
fails with `Peer invocation not supported in this context`. That is correct, not
a bug: run it through `capdag __CARTRIDGE_NAME__`, which hosts the cartridge and
routes the call.

A model cartridge providing `classify-en` must be installed. The first run
downloads the model, which is why the peer reports progress and why this
cartridge forwards it.

The cap is a *dev* cap: it is not published to the fabric, so you can develop
and run it locally as long as its alias (`__CARTRIDGE_NAME__`) does not collide
with a published cap.
"#,
                executable: false,
            },
            StubFile {
                dest: r#".gitignore"#,
                contents: r#"/target
cartridge.json
"#,
                executable: false,
            },
        ],
    },
    StubLanguage {
        id: r#"go"#,
        flag: r#"--go"#,
        display: r#"Go"#,
        entry: r#"__CARTRIDGE_NAME__"#,
        build: &[r#"go mod tidy"#, r#"go build -buildvcs=false -o __CARTRIDGE_NAME__ ."#],
        runtime_package: r#"github.com/machinefabric/capdag-go"#,
        runtime_registry: r#"git tag"#,
        runtime_install: r#"go mod tidy"#,
        files: &[
            StubFile {
                dest: r#"cartridge.go"#,
                contents: r#"// __CARTRIDGE_NAME__ — a MachineFabric cartridge (Go), scaffolded by `capdag new`.
//
// Reads UTF-8 text on stdin and emits a single tag word: `positive`,
// `neutral`, or `negative`.
//
// The judgment is made by a REAL model: this cartridge does no inference
// itself, it PEER-CALLS the `classify-en` cap and whichever model cartridge the
// host has installed answers it. That is the shape most cartridges want — own
// the domain logic, delegate the model — and it is what makes this the smallest
// useful cartridge rather than a toy: one custom cap, one Op that calls a peer,
// one manifest, one main().
//
// Develop it with:
//
//	go build -buildvcs=false -o __CARTRIDGE_NAME__ .   # the entry the host launches
//	capdag dev-install .               # install/update under the local `dev` slug
//	echo "I love this" | capdag __CARTRIDGE_NAME__
//	# edit the labels or the peer cap, then rebuild + re-install to update
package main

import (
	"encoding/json"
	"fmt"
	"os"

	capdag "github.com/machinefabric/capdag-go"
	"github.com/machinefabric/capdag-go/bifaci"
	"github.com/machinefabric/capdag-go/cap"
	"github.com/machinefabric/capdag-go/urn"
)

// --- The peer cap this cartridge delegates to. ------------------------------

// classifyCap is `classify-en` — closed-set labeling by a real model, provided
// by whichever model cartridge the host has installed.
//
// The labels are token-level constrained to the set we pass, so the answer is
// always one of them: a hallucinated label is impossible by construction, and
// this cartridge does not have to defend against one.
const classifyCap = `cap:classify;constrained;in="media:enc=utf-8";language=en;out="media:fmt=json;record;semantic-judgment"`

// The item being classified, and the allowed labels — both addressed by MEDIA
// URN, which is how a peer call names its arguments.
const (
	classifyItemMedia   = "media:enc=utf-8"
	classifyLabelsMedia = "media:enc=utf-8;label-set"
	labels              = "positive,neutral,negative"
)

// --- Op — implements the cap. -----------------------------------------------

type TagOp struct{}

func (op *TagOp) Perform(req *bifaci.Request) error {
	// Drain the (finite) input stream and decode as UTF-8 text.
	text, err := collectText(req.Frames())
	if err != nil {
		return err
	}

	output := req.Output()
	if err := output.StartUnbounded(false); err != nil {
		return err
	}

	// Ask the model cartridge. Arguments are addressed by media URN, not by
	// position.
	peerFrames, err := req.Peer().Invoke(classifyCap, []cap.CapArgumentValue{
		cap.NewCapArgumentValue(classifyItemMedia, []byte(text)),
		cap.NewCapArgumentValue(classifyLabelsMedia, []byte(labels)),
	})
	if err != nil {
		return fmt.Errorf("classify peer call failed: %w", err)
	}

	// FORWARDING collector: inference is slow and the model reports progress as
	// it goes. A plain CollectBytes REJECTS those LOG frames rather than
	// discarding them silently, so a peer that talks must be collected through a
	// forwarder. The peer's 0..1 progress is rescaled into the 0.0..0.9 slice of
	// ours, leaving the last tenth for our own work below.
	judgment, err := bifaci.DemuxPeerResponse(peerFrames).CollectBytesForwarding(output, 0.0, 0.9)
	if err != nil {
		return err
	}

	// The judgment record is {"label", "confidence", "reason"}; the label is one
	// of the labels we asked for.
	var record struct {
		Label string `json:"label"`
	}
	if err := json.Unmarshal(judgment, &record); err != nil {
		return fmt.Errorf("classify returned something that is not a semantic-judgment record: %w", err)
	}
	if record.Label == "" {
		return fmt.Errorf("the semantic-judgment record has no string `label` field")
	}

	output.Finish(1.0, fmt.Sprintf("classified as %s", record.Label))
	return output.EmitCbor(record.Label)
}

// collectText reassembles the request's CHUNK payloads, stopping at END.
func collectText(frames <-chan bifaci.Frame) (string, error) {
	var payload []byte
	for frame := range frames {
		switch frame.FrameType {
		case bifaci.FrameTypeChunk:
			if err := bifaci.VerifyChunkChecksum(&frame); err != nil {
				return "", fmt.Errorf("corrupted data: %w", err)
			}
			if frame.Payload == nil {
				continue
			}
			chunk, err := bifaci.DecodeChunkPayload(frame.Payload)
			if err != nil {
				return "", err
			}
			payload = append(payload, chunk...)
		case bifaci.FrameTypeEnd:
			return string(payload), nil
		}
	}
	return string(payload), nil
}

// --- URN + manifest. Media/cap URNs are seeded from the project name so they -
//     are unique per project and never collide with the published fabric. -----

const (
	inMedia  = "media:enc=utf-8;__CARTRIDGE_NAME__-input"
	outMedia = "media:enc=utf-8;__CARTRIDGE_NAME__-tag"
)

// capURN builds the cap URN ONCE via the builder, so the string we register
// with matches the runtime's canonical (alphabetically-sorted) byte form.
func capURN() *urn.CapUrn {
	built, err := urn.NewCapUrnBuilder().
		Marker("__CARTRIDGE_NAME__").
		InSpec(inMedia).
		OutSpec(outMedia).
		Build()
	if err != nil {
		panic(fmt.Sprintf("BUG: the scaffolded cap URN is invalid: %v", err))
	}
	return built
}

func buildManifest() *bifaci.CapManifest {
	c := cap.NewCap(capURN(), "__CARTRIDGE_NAME__", []string{"__CARTRIDGE_NAME__"})
	c.CapDescription = cap.StringPtr("Classify a piece of text as positive, neutral, or negative.")
	stdin := inMedia
	position := 0
	c.Args = []cap.CapArg{{
		MediaUrn: inMedia,
		Required: true,
		Sources: []cap.ArgSource{
			{Stdin: &stdin},
			{Position: &position},
		},
		ArgDescription: cap.StringPtr("UTF-8 text to classify."),
	}}
	c.Output = &cap.CapOutput{
		MediaUrn:          outMedia,
		OutputDescription: "One of the literal strings 'positive', 'neutral', or 'negative'.",
	}

	// Every cartridge advertises CAP_IDENTITY; the runtime auto-registers its handler.
	identityURN, err := urn.NewCapUrnFromString(capdag.CapIdentity)
	if err != nil {
		panic(fmt.Sprintf("BUG: CapIdentity is invalid: %v", err))
	}
	identity := cap.NewCap(identityURN, "Identity", []string{"identity"})

	return capdag.NewCapManifest(
		"__CARTRIDGE_NAME__",
		"0.1.0",
		"nightly", // 'nightly' or 'release'; nightly for dev.
		nil,       // nil => dev cartridge (installed locally).
		"Classify a piece of text as positive, neutral, or negative.",
		[]capdag.CapGroup{capdag.DefaultGroup([]cap.Cap{*identity, *c})},
	)
}

func main() {
	runtime, err := capdag.NewCartridgeRuntimeWithManifest(buildManifest())
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create runtime: %v\n", err)
		os.Exit(1)
	}
	runtime.RegisterOp(capURN().String(), &TagOp{})
	if err := runtime.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "runtime error: %v\n", err)
		os.Exit(1)
	}
}
"#,
                executable: false,
            },
            StubFile {
                dest: r#"go.mod"#,
                contents: r#"module __CARTRIDGE_NAME__

go 1.21

// Stamped from capdag-go's own version.txt, so the required version tracks what
// `dx publish capdag-go` tags rather than drifting until someone notices.
require github.com/machinefabric/capdag-go v1.345.9
"#,
                executable: false,
            },
            StubFile {
                dest: r#"README.md"#,
                contents: r#"# __CARTRIDGE_NAME__

A MachineFabric cartridge scaffolded by `capdag new`. It reads UTF-8 text on
stdin and emits `positive`, `neutral`, or `negative`.

## Develop

```bash
# 1. Build the entry the host launches:
go mod tidy
go build -buildvcs=false -o __CARTRIDGE_NAME__ .

# 2. Install this cartridge under the local `dev` slug:
capdag dev-install .

# 3. Run your cap through the capdag host:
echo "I love this" | capdag __CARTRIDGE_NAME__
# => positive

# 4. Edit the labels or the peer cap in cartridge.go, then re-run steps 1-2:
go build -buildvcs=false -o __CARTRIDGE_NAME__ . && capdag dev-install .
```

Unlike the Python cartridge, the entry here is a COMPILED binary, so an edit
does not reach the host until you rebuild. `capdag dev-install` installs the
binary named in the manifest, not the sources.

## It needs the host

This cartridge does not classify anything itself — it PEER-CALLS `classify-en`
and a model cartridge answers. Peer calls are routed by the capdag host, so
running the built entry directly (`./__CARTRIDGE_NAME__ __CARTRIDGE_NAME__`)
fails with `Peer invocation not supported in this context`. That is correct, not
a bug: run it through `capdag __CARTRIDGE_NAME__`, which hosts the cartridge and
routes the call.

A model cartridge providing `classify-en` must be installed. The first run
downloads the model, which is why the peer reports progress and why this
cartridge forwards it.

The cap is a *dev* cap: it is not published to the fabric, so you can develop
and run it locally as long as its alias (`__CARTRIDGE_NAME__`) does not collide
with a published cap.
"#,
                executable: false,
            },
            StubFile {
                dest: r#".gitignore"#,
                contents: r#"__CARTRIDGE_NAME__
cartridge.json
"#,
                executable: false,
            },
        ],
    },
    StubLanguage {
        id: r#"swift"#,
        flag: r#"--swift"#,
        display: r#"Swift"#,
        entry: r#".build/release/__CARTRIDGE_NAME__"#,
        build: &[r#"swift build -c release"#],
        runtime_package: r#"capdag-objc"#,
        runtime_registry: r#"git tag"#,
        runtime_install: r#"swift build (the dependency is declared in Package.swift)"#,
        files: &[
            StubFile {
                dest: r#"Sources/main.swift"#,
                contents: r#"// __CARTRIDGE_NAME__ — a MachineFabric cartridge (Swift), scaffolded by `capdag new`.
//
// Reads UTF-8 text on stdin and emits a single tag word: `positive`,
// `neutral`, or `negative`.
//
// The judgment is made by a REAL model: this cartridge does no inference
// itself, it PEER-CALLS the `classify-en` cap and whichever model cartridge the
// host has installed answers it. That is the shape most cartridges want — own
// the domain logic, delegate the model — and it is what makes this the smallest
// useful cartridge rather than a toy: one custom cap, one Op that calls a peer,
// one manifest, one main.
//
// Develop it with:
//     swift build -c release                    # the entry the host launches
//     capdag dev-install .                      # install under the local `dev` slug
//     echo "I love this" | capdag __CARTRIDGE_NAME__
//     # edit the labels or the peer cap, then re-run both to update

import Foundation
import Bifaci
import CapDAG
import Ops

// --- The peer cap this cartridge delegates to. ------------------------------

/// `classify-en` — closed-set labeling by a real model, provided by whichever
/// model cartridge the host has installed.
///
/// The labels are token-level constrained to the set we pass, so the answer is
/// always one of them: a hallucinated label is impossible by construction, and
/// this cartridge does not have to defend against one.
let classifyCap =
    "cap:classify;constrained;in=\"media:enc=utf-8\";language=en;"
    + "out=\"media:fmt=json;record;semantic-judgment\""

/// The item being classified, and the allowed labels — both addressed by MEDIA
/// URN, which is how a peer call names its arguments.
let classifyItemMedia = "media:enc=utf-8"
let classifyLabelsMedia = "media:enc=utf-8;label-set"

let labels = "positive,neutral,negative"

/// The shape `classify-en` answers with: {"label", "confidence", "reason"}.
struct SemanticJudgment: Decodable {
    let label: String
}

// --- Op — implements the cap. -----------------------------------------------

struct TagOp: Op, Sendable {
    typealias Output = Void

    func perform(dry: DryContext, wet: WetContext) async throws {
        let req = try wet.getRequired(CborRequest.self, for: WET_KEY_REQUEST)
        // Drain the (finite) input stream and decode as UTF-8 text.
        let payload = try req.takeInput().collectAllBytes()
        let text = String(decoding: payload, as: UTF8.self)

        let out = req.output()
        try out.start(isSequence: false)

        // Ask the model cartridge. Arguments are addressed by media URN, not by
        // position.
        let response = try req.peer().callWithBytes(
            capUrn: classifyCap,
            args: [
                (mediaUrn: classifyItemMedia, data: Data(text.utf8)),
                (mediaUrn: classifyLabelsMedia, data: Data(labels.utf8)),
            ]
        )

        // FORWARDING collector: inference is slow and the model reports progress
        // as it goes. A plain collectBytes REJECTS those LOG frames rather than
        // discarding them silently, so a peer that talks must be collected
        // through a forwarder. The peer's 0..1 progress is rescaled into the
        // 0.0..0.9 slice of ours, leaving the last tenth for our own work below.
        let judgment = try response.collectBytesForwarding(
            output: out, progressBase: 0.0, progressWeight: 0.9)

        // The judgment record is {"label", "confidence", "reason"}; the label is
        // one of the labels we asked for.
        let record: SemanticJudgment
        do {
            record = try JSONDecoder().decode(SemanticJudgment.self, from: judgment)
        } catch {
            throw CartridgeRuntimeError.handlerError(
                "classify returned something that is not a semantic-judgment record: \(error)")
        }

        out.finish(progress: 1.0, message: "classified as \(record.label)")
        try await out.emitCbor(.utf8String(record.label))
    }

    func metadata() -> OpMetadata {
        OpMetadata.builder("TagOp")
            .description("Classify text as positive / neutral / negative")
            .build()
    }
}

// --- URN + manifest. Media/cap URNs are seeded from the project name so they -
//     are unique per project and never collide with the published fabric. -----

let inMedia = "media:enc=utf-8;__CARTRIDGE_NAME__-input"
let outMedia = "media:enc=utf-8;__CARTRIDGE_NAME__-tag"

/// Build the cap URN ONCE via the builder, so the string we register with
/// matches the runtime's canonical (alphabetically-sorted) byte form.
func capURN() -> String {
    do {
        // Two Objective-C bridging details: `+builder` imports as `init()`, and
        // `build:` takes an NSError** which imports as a throwing call rather
        // than an inout argument.
        let urn = try CSCapUrnBuilder()
            .marker("__CARTRIDGE_NAME__")
            .inSpec(inMedia)
            .outSpec(outMedia)
            .build()
        return urn.toString()
    } catch {
        fatalError("BUG: the scaffolded cap URN is invalid: \(error)")
    }
}

func buildManifest() -> Manifest {
    let cap = CapDefinition(
        urn: capURN(),
        title: "__CARTRIDGE_NAME__",
        aliases: ["__CARTRIDGE_NAME__"],
        capDescription: "Classify a piece of text as positive, neutral, or negative.",
        args: [
            CapArg(
                mediaUrn: inMedia,
                required: true,
                sources: [.stdin(inMedia), .positional(0)],
                argDescription: "UTF-8 text to classify."
            )
        ],
        output: CapOutput(
            mediaUrn: outMedia,
            outputDescription: "One of the literal strings 'positive', 'neutral', or 'negative'."
        )
    )

    // Every cartridge advertises CAP_IDENTITY; the runtime auto-registers its handler.
    let identity = CapDefinition(urn: CSCapIdentity, title: "Identity", aliases: ["identity"])

    return Manifest(
        name: "__CARTRIDGE_NAME__",
        version: "0.1.0",
        channel: "nightly",   // 'nightly' or 'release'; nightly for dev.
        registryURL: nil,     // nil => dev cartridge (installed locally).
        description: "Classify a piece of text as positive, neutral, or negative.",
        capGroups: [CapGroup(name: "default", caps: [identity, cap])]
    )
}

// --- main -------------------------------------------------------------------

let manifestData = try JSONEncoder().encode(buildManifest())
let runtime = CartridgeRuntime(manifest: manifestData)
runtime.register_op_type(capUrn: capURN(), make: TagOp.init)

do {
    try runtime.run()
} catch {
    FileHandle.standardError.write(Data("[__CARTRIDGE_NAME__] Runtime error: \(error)\n".utf8))
    exit(1)
}
"#,
                executable: false,
            },
            StubFile {
                dest: r#"Package.swift"#,
                contents: r#"// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "__CARTRIDGE_NAME__",
    platforms: [
        .macOS(.v13)
    ],
    dependencies: [
        .package(url: "https://github.com/machinefabric/capdag-objc.git", from: "1.405.10"),
        .package(url: "https://github.com/jowharshamshiri/ops-objc.git", from: "1.18.132"),
    ],
    targets: [
        .executableTarget(
            name: "__CARTRIDGE_NAME__",
            dependencies: [
                .product(name: "Bifaci", package: "capdag-objc"),
                .product(name: "CapDAG", package: "capdag-objc"),
                .product(name: "Ops", package: "ops-objc"),
            ],
            path: "Sources"
        )
    ]
)
"#,
                executable: false,
            },
            StubFile {
                dest: r#"README.md"#,
                contents: r#"# __CARTRIDGE_NAME__

A MachineFabric cartridge scaffolded by `capdag new`. It reads UTF-8 text on
stdin and emits `positive`, `neutral`, or `negative`.

macOS only — the Swift cartridge runtime (`capdag-objc`) builds against the
Apple toolchain.

## Develop

```bash
# 1. Build the entry the host launches:
swift build -c release

# 2. Install this cartridge under the local `dev` slug:
capdag dev-install .

# 3. Run your cap through the capdag host:
echo "I love this" | capdag __CARTRIDGE_NAME__
# => positive

# 4. Edit the labels or the peer cap in Sources/main.swift, then re-run steps 1-2:
swift build -c release && capdag dev-install .
```

Unlike the Python cartridge, the entry here is a COMPILED binary, so an edit
does not reach the host until you rebuild.

## It needs the host

This cartridge does not classify anything itself — it PEER-CALLS `classify-en`
and a model cartridge answers. Peer calls are routed by the capdag host, so
running the built entry directly (`./__CARTRIDGE_NAME__ __CARTRIDGE_NAME__`)
fails with `Peer invocation not supported in this context`. That is correct, not
a bug: run it through `capdag __CARTRIDGE_NAME__`, which hosts the cartridge and
routes the call.

A model cartridge providing `classify-en` must be installed. The first run
downloads the model, which is why the peer reports progress and why this
cartridge forwards it.

The cap is a *dev* cap: it is not published to the fabric, so you can develop
and run it locally as long as its alias (`__CARTRIDGE_NAME__`) does not collide
with a published cap.
"#,
                executable: false,
            },
            StubFile {
                dest: r#".gitignore"#,
                contents: r#".build/
.swiftpm/
cartridge.json
"#,
                executable: false,
            },
        ],
    },
];
